const domainDesc = {
  market: "Toàn cảnh thị trường: chỉ số, độ rộng, vĩ mô, dòng tiền theo ngành, hàng hóa liên kết và tín hiệu bất thường toàn thị trường.",
  price: "Xem giá real-time, phân tích kỹ thuật, và luyện tập giao dịch không rủi ro qua mô phỏng.",
  company: "Hồ sơ toàn diện từng doanh nghiệp: tài chính, định giá, và điểm chất lượng theo các mô hình học thuật.",
  idea: "Khuyến nghị đầu tư kết hợp chuyên gia và mô hình định lượng, cùng công cụ so sánh hiệu suất.",
  tools: "Bộ công cụ định lượng: lọc cổ phiếu, viết công thức riêng, và kiểm định chiến lược trên dữ liệu lịch sử.",
  knowledge: "Học khái niệm tài chính ngay trong luồng sử dụng, và hỏi-đáp trực tiếp với trợ lý AI.",
  personal: "Không gian cá nhân hóa: danh mục theo dõi, bản tin riêng, và nhật ký quyết định đầu tư.",
};

const featDesc = {
  vimo:"Ma trận tác động 2 chiều: chiều hướng × mức độ ảnh hưởng của từng yếu tố vĩ mô tới VN-Index.",
  lichkt:"Lịch công bố dữ liệu kinh tế Việt Nam, Mỹ, Trung Quốc.",
  thitruong:"Chỉ số Sợ hãi/Tham lam, độ rộng thị trường, Top ảnh hưởng Index.",
  nganh:"Dòng tiền theo từng ngành, xu hướng tích lũy nhiều tuần.",
  hanghoa:"Giá hàng hóa quốc tế, liên kết trực tiếp tới cổ phiếu/ngành trong nước.",
  marketwatch:"8 chỉ báo thị trường: độ rộng, thanh khoản, khối ngoại, tự doanh, vốn hóa...",
  marketwatchnganh:"Đóng góp của từng ngành vào chỉ số theo nhiều khung thời gian.",
  gdcdlon:"Theo dõi giao dịch cổ đông lớn và nội bộ toàn thị trường.",
  tinhieunoibo:"Tự động quét và gắn cờ mã có dấu hiệu bất thường mỗi phiên.",
  banggia:"Bảng giá 3 cấp, đa tài sản, với watchlist cá nhân.",
  ptkt:"Biểu đồ nến kèm chỉ báo kỹ thuật và dữ liệu giao dịch NĐTNN.",
  giaodichao:"Mô phỏng mua bán theo giá thật, không rủi ro.",
  tinhieumohinh:"Các tín hiệu định lượng theo từng mô hình đã kiểm định.",
  giaodichaonangcao:"Giao dịch ảo có bảng xếp hạng và huy hiệu thi đua nội bộ.",
  dn360:"Hồ sơ 360° một doanh nghiệp: tài chính, hồ sơ, cảnh báo rủi ro, sự kiện.",
  dinhgia:"4 phương pháp định giá kết hợp, có thể tùy chỉnh giả định.",
  sosanh4loai:"So sánh chỉ tiêu đặc trưng theo 4 loại hình DN với trung bình ngành.",
  chisonganhang:"Xu hướng 1 chỉ số qua nhiều ngân hàng cùng lúc, nhiều năm.",
  duphong:"Dự phóng lợi nhuận và tính PE Forward theo giả định tự nhập.",
  diemchatluong:"F-Score, Magic Formula, Beneish M-Score — 3 mô hình học thuật quốc tế.",
  ytuong:"Danh sách khuyến nghị đa mô hình, có tỷ lệ thắng lịch sử.",
  sosanhreturn:"So sánh hiệu suất sinh lời giữa mã/ngành/danh mục với benchmark.",
  phantichnganh:"6 chỉ tiêu chuẩn phân tích ở cấp ngành.",
  phantichdanhmuc:"Theo dõi và phân tích hiệu suất danh mục cá nhân.",
  multistrategy:"Kết hợp nhiều công thức theo trọng số để backtest như 1 chiến lược.",
  boloc:"3 cấp độ: point-and-click, viết công thức, công thức nâng cao.",
  backtestcongthuc:"Kiểm định 1 công thức trên dữ liệu lịch sử, có Stop Loss/Take Profit.",
  backtesttudong:"Tự động tính tỷ lệ thắng cho mọi công thức đang lưu.",
  chocongthuc:"Chia sẻ và tái sử dụng công thức giữa các thành viên nội bộ.",
  nhan:"Mọi số liệu đều có nhãn nguồn và thời điểm cập nhật.",
  trungtamkienthuc:"Bài viết giải thích khái niệm, đối chiếu công thức thật đang chạy.",
  tudien:"Giải thích thuật ngữ ngay tại chỗ khi hover vào số liệu.",
  chatbotv1:"Hỏi nhanh, hệ thống trả kết quả tra cứu có cấu trúc.",
  diengiaiAI:"AI tự viết 2-3 câu diễn giải cho mỗi kết quả phân tích.",
  kienthucmorong:"Bài viết chuyên sâu về F-Score, Magic Formula, Backtest.",
  chatbotv2:"Hỏi tự do, AI tổng hợp từ toàn bộ dữ liệu hệ thống.",
  chatbotchudong:"AI chủ động đề xuất insight không cần chờ được hỏi.",
  danhmucquantam:"Watchlist cá nhân, nhiều danh mục cùng lúc.",
  bantin:"Bản tin sáng riêng theo watchlist của từng người.",
  dashboardvaitro:"Màn hình mặc định khác nhau theo vai trò công việc.",
  nhatky:"Ghi chú lý do vào/ra lệnh, theo dõi kỷ luật giao dịch.",
};
